"""Initial migration

Revision ID: 7db2c460da00
Revises: 
Create Date: 2025-07-05 09:42:15.462572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db2c460da00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_shares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_delete', sa.Boolean(), nullable=True))

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('original_filename')

    with op.batch_alter_table('file_shares', schema=None) as batch_op:
        batch_op.drop_column('can_delete')

    # ### end Alembic commands ###
